all:
	g++ -o prog main.o DateUtils.o Docente.o Leitor.o StringUtils.o Tokenizer.o Ocorrencia.o Publicacao.o Qualis.o Veiculo.o Regras.o ItemListaPublicacoes.o Utils.o ItemEstPub.o Recredenciamento.o EscritorCsv.o Global.o
objs:
	g++ -c main.cpp DateUtils.cpp Docente.cpp Leitor.cpp StringUtils.cpp Tokenizer.cpp Ocorrencia.cpp Publicacao.cpp Qualis.cpp Veiculo.cpp Regras.cpp  ItemListaPublicacoes.cpp Utils.cpp ItemEstPub.cpp Recredenciamento.cpp EscritorCsv.cpp Global.cpp
	
	